// packages/react-tmap/src/TmapCardinalArrow/TmapCardinalArrow.tsx
import './TmapCardinalArrow.scss';
import React, { useState, useEffect,useContext ,useRef} from 'react';

import {MapContext} from '../utils/context'
interface marker{
  points:any,
  [propName: string]: any;
}

const TmapCardinalArrow: React.FC<marker> = ({points,children}) => {
  let {$mapApi,$tmap} = useContext(MapContext)
  let domRef = useRef(null);
  useEffect(()=>{
    let $tmapComponent:any = null;
    if($tmap){
      let lnglats = points.map((point:any[]) => {
        return point instanceof T.dq ? point: new T.LngLat(point[0],point[1])
      })
      $tmapComponent = new ($mapApi as any).CardinalCurveArrow( lnglats,{
        color: 'red',
        weight: 3,
        opacity:  1,
        fillColor:  '#FFFFFF',
        fillOpacity: 0
      });
      ($tmap as any).addOverLay($tmapComponent);
    }
    return ()=>{
      if( $tmapComponent && $tmap){
        $tmapComponent && ($tmap as any).removeLayer($tmapComponent)
        $tmapComponent = null;
      }
    }
  },[$tmap,points])

  return (null);
};

export default TmapCardinalArrow;

// packages/tmap/src/tmap-cardinal-arrow/main.vue
<script>
export default {
  name: "tmapCardinalArrow",
  inject: {
    $tmapPromiseLazy: { default: '' }
  },
  props: {
    points: {
      type:Array,
      default:()=>[]
    },
    config:{
      type:Object,
      default:()=>{}
    }
  },
  computed:{
    mergeConfig(){
      return {...this.defaultConfig,...this.config}
    }
  },
  watch:{
    points:{
      deep:true,
      handler(val){
        if(val.length){
          if(this.$tmap && this.$mapApi){
            this.addPoints();
          }else{
            this.$tmapPromiseLazy.then(({map,mapApi}) => {
              this.$tmap = map;
              this.$mapApi = mapApi;
              this.addPoints();
            })
          }


        }

      }
    }
  },
  data(){
    return {
      $tmap:null,
      $tmapComponent:null,
      $mapApi : null,
      defaultConfig:{
        color: 'red',
        weight: 3,
        opacity:  1,
        fillColor:  '#FFFFFF',
        fillOpacity: 0
      }
    }
  },
  created(){

  },
  render(){
    return null
  },
  mounted(){
    this.$tmapPromiseLazy.then(({map,mapApi}) => {
      this.$tmap = map;
      this.$mapApi = mapApi;
    })
  },

  destroyed() {
    this.removeaddPoints();
  },
  methods:{
    initComponent() {
      this.removeaddPoints();
      let {$tmap,$mapApi,points} = this;
      this.$tmapComponent = new $mapApi.CardinalCurveArrow(points,this.mergeConfig);
      console.log(this.$tmapComponent)
      $tmap.addOverLay(this.$tmapComponent);
    },
    addPoints(){
      this.initComponent();
    },
    removeaddPoints(){
      this.$tmapComponent && this.$tmap.removeLayer(this.$tmapComponent)
      this.$tmapComponent = null;
    },
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}
</style>
