// packages/hoipack-cli/site/react/App.tsx
import React, { useState, useEffect,useRef,useReducer } from 'react';
import {Tmap,TmapMarker,TmapPolygon} from '@/index';

interface interfaceT{
  [propName: string]: any;
}

const TianMap: React.FC<interfaceT> = () => {
  let mapRef = useRef(null);
  let [monitorMarker,setMonitorMarker] = useState([])
  let [mapCenter] = useState([107,32])
  let [zoom] = useState([])

  useEffect(()=>{
    setTimeout(()=>{
      let markers = []
      for (var i = 0; i < 1; i++) {
        let lng = 104.06 - (Math.random() * 1).toFixed(6);
        let lat = 30.67	 - (Math.random() * 1).toFixed(4);
        var point = [lng, lat];
       
        markers.push({
          position:point,
          data:{
            name:lng
          },
        })
      }
      setMonitorMarker(markers)
      console.log(markers)
    },2000)
  },[])

  let color1 = {
    color:'red'
  }

  return (
    <div className="tian-map">
      <Tmap ref={mapRef} center={mapCenter} zoom={zoom}>
        {
          monitorMarker.map((marker: any) => {
            return (
              <TmapMarker marker={marker} key={JSON.stringify(marker)}>
                <div style={color1}>asdfas</div>
              </TmapMarker>
            )
          })
        }
        {/* {
          <TmapPolygon points={ARPolygon}></TmapPolygon>
        } */}
      </Tmap>
    </div>
  );
};

export default TianMap;

// packages/hoipack-cli/site/App.vue
<template>
  <div>
   <tmap ref="map">
      <!-- <tmap-marker v-for="(marker,index) in markers" :key="index" :marker="marker">
        <template #default="marker">
          <div style="color:red;" @click="clickMarker(marker)">点{{marker.keyData.name}}</div>
        </template>
      </tmap-marker> -->
      <tmap-cluster :markers="markers">
        <template #marker="marker">
          <div style="color:red;" @click="clickMarker(marker)">asdfas</div>
        </template>
        <template #default="{markerNum}">
          <div style="color:yellow;">
            点{{markerNum}}
          </div>
        </template>
      </tmap-cluster>
      <tmap-info-window :position="infoWindow.position" :keyData="infoWindow.data" :visible="infoWindow.visible">
        <template #default="marker">
          <div>
            <p @click="closeMarker(infoWindow)">
              sadfasdfa
            </p>
            
            <div style="color:yellow;" >{{infoWindow}}</div>
            <div>{{marker}}</div>
          </div>
            
        </template>
      </tmap-info-window>
      
      <!-- <tmap-cardinal-arrow :points="markers.map(v =>v.position)" />
      <tmap-polygon :points="markers.map(v =>v.position)" />
      <tmap-polyline :points="markers.map(v =>v.position)" /> -->


   </tmap>
  </div>
</template>

<script>

  export default {
    name: 'app',
    data () {
      return {
        markers:[],
        infoWindow:{
          position:[],
          data:{},
          visible:false
        }
      }
    },
    mounted () {
      setTimeout(()=>{
        for (var i = 0; i < 1000; i++) {
          let lng = 104.06 - (Math.random() * 1).toFixed(6);
          let lat = 30.67	 - (Math.random() * 1).toFixed(4);
          var point = [lng, lat];
          this.markers.push({
            position:point,
            data:{
              name:lng
            },
          })
        }
      
      },2000)
    },
    methods: {
      clickMarker(marker){
        console.log(marker)
        this.infoWindow.position = marker.position
        this.infoWindow.data = marker.keyData
        this.infoWindow.visible = true
        
      },
      closeMarker(){
        this.infoWindow.visible = false
      }
    }
  }
</script>

<style scoped>
  

</style>
