// packages/vue3-tmap/tmap-cluster/TmapCluster.vue
<script>
import { MarkerClusterer } from "../utils/MarkerClusterer";
import { ProxyCluster } from "../utils/overlay/mapOverlay";
export default {
  name: "tmapCluster",
  inject: {
    $tmapPromiseLazy: { default: "" },
    $tmapPromiseTest: { default: "" }
  },
  props: {
    markers: {
      type: Array,
      default: () => [],
    },
  },
  watch: {
    markers: {
      deep: true,
      async handler(val) {
        await this.$tmapPromiseLazy;
        this.$tmapComponent.clearMarkers()
        this.addMarkers(val);
      },
    },
  },
  data() {
    return {
      $tmap: null,
      $tmapComponent: null,
      $mapApi: null,
    };
  },
  created() {
    
  },
  render() {
    return null;
  },
  mounted() {
    this.$tmapPromiseLazy.then(({ map, mapApi }) => {
      this.$tmap = map;
      this.$mapApi = mapApi;
      this.initMarkerClusterer()
    });
    console.log(this.$tmapPromiseTest,'$tmapPromiseTest')
  },

  unmounted() {
    this.removeOverlay();
  },
  methods: {
    addMarkers(arr) {
      let markers = arr.map((data) => {
        return this.initMarker(data);
      });
      this.$tmapComponent.addMarkers(markers)
    },
    initMarkerClusterer(){
      this.$tmapComponent = new MarkerClusterer(this.$tmap, {
        markers:[],
        clusterMarker: this.initClusterMarker,
      });
    },
    initMarker(vm) {
      return new ProxyCluster(this.$slots.marker,{
        position:vm.position,
        keyData:vm.data
      });
    },
    initClusterMarker() {
      return new ProxyCluster(this.$slots.default,
      {
        position:[104.06, 30.67],
        data:{}
      });
    },
    removeOverlay() {
      this.$tmapComponent && this.$tmapComponent.clearMarkers();
      this.$tmapComponent = null;
    }
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}
</style>

// packages/react-tmap/src/TmapCluster/TmapCluster.tsx
import './TmapCluster.scss';
import React, { useState, useEffect,useContext ,useRef} from 'react';
import {createPortal} from 'react-dom';
import {MapContext} from '../utils/context'

import { MarkerClusterer } from "../utils/MarkerClusterer";
import { ProxyCluster } from "../utils/overlay/mapOverlay";

interface marker{
  markers:any,
  [propName: string]: any;
}
const TmapCluster: React.FC<marker> = ({markers = [],children}) => {
  let {$mapApi,$tmap} = useContext(MapContext)

  let markerEl = document.createElement('div')
  markerEl.classList.add('tmap-marker')

  let clusterEl = document.createElement('div')
  clusterEl.classList.add('tmap-cluster')
  
  useEffect(()=>{
    if($tmap){
      let markerPane = ($tmap as any).getPanes().markerPane;
      markerPane.appendChild(markerEl)
      markerPane.appendChild(clusterEl)
      addMarkers(markers);
    }
    return ()=>{
      if($tmap){
        let markerPane = ($tmap as any).getPanes().markerPane;
        markerPane.removeChild(markerEl)
        markerPane.removeChild(clusterEl)
      }
    }
  },[$tmap,markers])
  


  const  initMarker = (vm:any) => {
    console.log(markerEl,'markerEl')
    return new (ProxyCluster as any)(
      markerEl,
      {
        position:vm.position,
        keyData:vm.data
      }
    );
  }

  const initClusterMarker = () =>  {
    console.log(clusterEl,'clusterEl')
    return new (ProxyCluster as any)(
      clusterEl,
    {
      position:[104.06, 30.67],
      data:{}
    });
  }

  const addMarkers = (arr:any) => {
    let markers = arr.map((data:any) => {
      return initMarker(data);
    });
    new MarkerClusterer($tmap, {
      markers,
      clusterMarker: initClusterMarker,
    });
  }

  const renderChild = (childrens:any):any => {

    let marker:any = null;
    let cluster:any = null;

    childrens.forEach((child:any) => {
      if(child?.props?.slot === 'marker'){
        marker = marker;
      }else{
        cluster = child
      }
    })
    let ss = createPortal(
      marker,
      markerEl
    )
    let sd = createPortal(
      cluster,
      clusterEl
    )
    console.log(sd,ss,'ss')

    return [
      ss,
      sd
    ]
    
  }

  return (
   <>
    {renderChild(children)}  
   </>
  )   
};

export default TmapCluster;
