// packages/tmap/src/packages/tmap/main.vue
<template>
  <div class="tmap">
   <slot></slot>
   <div class="map-container" ref="tmap"></div>
  </div>
</template>

<script>
import Emitter from '@/libs/mixins/emitter'
import CONSTANTS from '@/libs/config/constant'
import loadTmapApi from '@/libs/utils/initializer'
import promiseLazyFactory from '@/libs/utils/promise-lazy'

import config from '@/libs/config/map';

const promiseLazyCreator  = promiseLazyFactory(loadTmapApi)
const tmapApiPromiseLazy = promiseLazyCreator({
  tk: CONSTANTS.TMAP_KEY,
});



export default {
  name: "tmap",
  mixins:[Emitter],
  props: {
    center:{
      type:Array,
      default:()=>[config.deFaultLng,config.deFaultLat]
    },
    zoom:{
      type:[Number,String],
      default:config.zoom
    },
  },
  provide () {
    this.$tmapPromiseLazy = new Promise((resolve, reject) => {
      this.$mapPromiseDeferred = { resolve, reject }
    })
    return {
      $tmapPromiseLazy: this.$tmapPromiseLazy
    }
  },
  watch:{
    center([lng,lat]){
      this.$tmap.panTo(new this.$mapApi.LngLat(lng, lat),this.zoom);
    },
    zoom(val){
      let [lng, lat] = this.center;
      this.$tmap.panTo(new this.$mapApi.LngLat(lng, lat),val);
    }
  },
  data(){
    return {
      $tmap:null,
      $mapApi:null,
      $mapPromiseDeferred:null,
      $tmapPromiseLazy:null
    }
  },
  mounted(){
    tmapApiPromiseLazy().then(mapApi => {
      this.$mapApi = mapApi;
      this.initMap(mapApi)
      // this.broadcast('tmapMarker',CONSTANTS.TMAP_READY_EVENT,[this.$tmap,mapApi])
      // this.broadcast('tmapInfoWindow',CONSTANTS.TMAP_READY_EVENT,[this.$tmap,mapApi])
    })
  },
  methods:{
    initMap(mapApi){
      let {
        tileUrl,
        fontLayerUrl,
        minZoom,
        maxZoom,
        zoom,
        deFaultLng,
        deFaultLat
      } = config;

      let tile = new mapApi.TileLayer(tileUrl)
      let fontLayer = new mapApi.TileLayer(fontLayerUrl)
      let layConfig = {
        layers: [tile, fontLayer],
        minZoom,
        maxZoom,
        zoom,
        center: new mapApi.LngLat(deFaultLng, deFaultLat)
      }
      
      //初始化地图对象
      this.$tmap = new mapApi.Map(this.$refs.tmap, layConfig);
      this.$mapPromiseDeferred.resolve({map:this.$tmap,mapApi})
    },
    markerCenterAndZoom([lng,lat] = [],offset = 300){
      let getZoom = this.$tmap.getZoom();
      var pointer = this.$tmap.lngLatToLayerPoint({lat,lng});
      pointer.y -= offset;
      let center = this.$tmap.layerPointToLngLat(pointer);
      this.$tmap.panTo(center,getZoom);
    },
  }
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
.tmap{
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  z-index: 1;
  // /deep/ * {
  //   box-sizing: content-box;
  // }
  ::v-deep .tdt-bottom.tdt-left{
    display: none;
  }
  .map-container{
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    z-index: 2;
  }
}
</style>

// packages/react-tmap/src/Tmap/Tmap.tsx
import './Tmap.scss';
import React,{useState,useEffect,useRef,useImperativeHandle} from 'react';

import {MapContext} from '../utils/context'

import CONSTANTS from '../utils/config/constant'
import loadTmapApi from '../utils/initializer'
import promiseLazyFactory from '../utils/promise-lazy'

import config from '../utils/config/map';

const promiseLazyCreator  = promiseLazyFactory(loadTmapApi)
const tmapApiPromiseLazy = promiseLazyCreator({
  tk: CONSTANTS.TMAP_KEY,
});

interface MapPros{
  [propName: string]: any;
}

interface MapRef{
  [propName: string]: any;
}

const TampRef= React.forwardRef<MapRef, MapPros>(({children , center = [config.deFaultLng,config.deFaultLat],zoom = config.zoom},ref) => {
  
  let [$tmap,set$tmap] = useState<any>(null)
  let [$mapApi,set$mapApi] = useState<any>(null)

  const tmap = useRef(null);

  const initMap = (mapApi:any) => {
    let {
      tileUrl,
      fontLayerUrl,
      minZoom,
      maxZoom,
      zoom,
      deFaultLng,
      deFaultLat
    } = config;

    let tile = new mapApi.TileLayer(tileUrl)
    let fontLayer = new mapApi.TileLayer(fontLayerUrl)
    let layConfig = {
      layers: [tile, fontLayer],
      minZoom,
      maxZoom,
      zoom,
      center: new mapApi.LngLat(deFaultLng, deFaultLat)
    }

    //初始化地图对象
    set$tmap(new mapApi.Map(tmap.current, layConfig))

  }

  const markerCenterAndZoom = (position:any,offset = 300) => {
    let [lng,lat] = position;
    let getZoom = $tmap.getZoom();
    var pointer = $tmap.lngLatToLayerPoint({lat,lng});
    pointer.y -= offset;
    let center = $tmap.layerPointToLngLat(pointer);
    $tmap.panTo(center,getZoom);
  }

  const getMap = () => {
    return $tmap;
  }

  useEffect(()=>{
    tmapApiPromiseLazy().then((mapApi:any) => {
      set$mapApi(mapApi)
      initMap(mapApi)
    })
  },[1])

  useEffect(()=>{
    if($tmap && $mapApi){
      let [lng, lat] = center;
      $tmap.panTo(new $mapApi.LngLat(lng, lat),zoom);
    }

  },[center,zoom])

  useImperativeHandle(ref,()=>{
    return {
      markerCenterAndZoom,
      getMap
    }
  })

  return (
    <div className="tmap">
      <MapContext.Provider value={{$tmap,$mapApi}}>
        {children}
      </MapContext.Provider>
     
      <div className="map-container" ref={tmap}></div>
    </div>
  );
})

export default TampRef;
