// packages/vue-tmap/src/tmap-marker/main.vue
<script>
import {ProxyMarker} from '../utils/overlay/mapOverlay'

export default {
  name: "tmapMarker",
  inject: {
    $tmapPromiseLazy: { default: '' }
  },
  props: {
    marker: {
      type:Object,
      default:()=>{}
    }
  },
  watch:{
    marker:{
      deep:true,
      handler(val){
       
       
      }
    }
    
  },
  data(){
    return {
      $tmap:null,
      $tmapComponent:null,
      $mapApi : null,
    }
  },
  render(){
    return null
  },
  mounted(){
    this.$tmapPromiseLazy.then(({map,mapApi}) => {
      this.$tmap = map;
      this.$mapApi = mapApi;
      this.initComponent();
    })
  },
  
  destroyed() {
    this.removeOverlay();
  },
  methods:{
    initComponent() {
      this.$tmapComponent = this.initMarker();
      this.$tmap.addOverLay(this.$tmapComponent);
    },
    initMarker(){
      return new ProxyMarker( this.$scopedSlots.default,{
        position:this.marker.position,
        keyData:this.marker.data
      })
    },
    removeOverlay(){
      this.$tmapComponent && this.$tmap.removeLayer(this.$tmapComponent)
      this.$tmapComponent = null;
    }
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">

</style>

// packages/react-tmap/src/TmapMarker/TmapMarker.tsx
import './TmapMarker.scss';
import React, { useState, useEffect,useContext ,useRef} from 'react';
import {ProxyMarker} from '../utils/overlay/mapOverlay'
import {MapContext} from '../utils/context'

interface marker{
  marker:any,
  events?:any,
  render():any,
  [propName: string]: any;
}

const TmapMarker: React.FC<marker> = ({marker,render,events,children},ref) => {
  let {$tmap} = useContext(MapContext)
  const createMarker = (data:any) => {
    let marker = new (ProxyMarker as any)(render,{
      position:data.position,
      keyData:data.data,
    },events);
    ($tmap as any).addOverLay(marker);
    return marker
  }

  useEffect(()=>{
    let $tmapComponent:any = null;
    if($tmap){
      $tmapComponent = createMarker({
        position:marker.position,
        data:marker.data
      });
      
    }
    return ()=>{
      if( $tmapComponent && $tmap){
        $tmapComponent && ($tmap as any).removeLayer($tmapComponent)
        $tmapComponent = null;
      }
    }
  },[$tmap])

  return null
};

export default TmapMarker;
