// packages/hoipack-cli/site/react/App.tsx
import React, { useState, useEffect,useRef,useReducer } from 'react';
import {Tmap,TmapMarker,TmapPolygon,TmapCluster,TmapInfoWindow} from '@/index';

interface interfaceT{
  [propName: string]: any;
}

const TianMap: React.FC<interfaceT> = () => {
  let mapRef = useRef(null);
  let [monitorMarker,setMonitorMarker] = useState([])
  let [mapCenter] = useState([107,32])
  let [zoom] = useState([])
  let [position,setPostion] = useState([107,32])
  let [data,setData] = useState({
    name:'name11'
  })
  let [visible,setVisible] = useState(false)

  useEffect(()=>{
    let markers = [];

    for (var i = 0; i < 10; i++) {
      let lng = 104.06 - (Math.random() * 1).toFixed(6);
      let lat = 30.67	 - (Math.random() * 1).toFixed(4);
      var point = [lng, lat];
     
      markers.push({
        position:point,
        data:{
          name:lng
        },
      })
    }
    setMonitorMarker(markers)

    // setTimeout(()=>{
    //   markers = []
    //   for (var i = 0; i < 2; i++) {
    //     let lng = 104.06 - (Math.random() * 1).toFixed(6);
    //     let lat = 30.67	 - (Math.random() * 1).toFixed(4);
    //     var point = [lng, lat];
       
    //     markers.push({
    //       position:point,
    //       data:{
    //         name:lng
    //       },
    //     })
    //   }
    //   setMonitorMarker(markers)
    // },5000)
  },[])

  let color1 = {
    color:'red'
  }
  let color2 = {
    color:'yellow'
  }

  const clickMarker = (marker)=>{
    setPostion(marker.lnglat)
    setData(marker.keyData)
    setVisible(true)
  }
  const closeOpen = ()=>{
    setData({
      name:'21321'
    })
    setVisible(false)
  }

  return (
    <div className="tian-map">
      <Tmap ref={mapRef} center={mapCenter} zoom={zoom}>
        {/* {
          monitorMarker.map((marker: any,index) => {
            return (
              <TmapMarker marker={marker} key={index} >
                <div style={color1} onClick={()=>{clickMarker(marker)}}>asdfas</div>
              
              </TmapMarker>
            )
          })
        } */}
        <TmapCluster markers={monitorMarker} onClick={clickMarker}>
          <div slot="marker" style={color1}>
            <div>asdfas</div>
            <div>asdfas</div>
          </div>
          <div style={color2} >
            点
          </div>
        </TmapCluster>
        {
          <TmapInfoWindow position={position} infoData={data} visible={visible}>
            <div style={color2} onClick={()=>{closeOpen()}}>
              <div>{data.name}</div>
              <div>5454</div>
            </div>
          </TmapInfoWindow>
        }
        {
          <TmapPolygon points={monitorMarker.map(v =>v.position)}></TmapPolygon>
        }
      </Tmap>
    </div>
  );
};

export default TianMap;

// packages/hoipack-cli/site/vue3/App.vue
<template>
  <div>
   <tmap ref="map">
      <!-- <tmap-marker v-for="(marker,index) in markers" :key="index" :marker="marker">
        <template #default="marker">
          <div style="color:red;" @click="clickMarker(marker)">点{{marker.keyData.name}}</div>
        </template>
      </tmap-marker> -->
      <tmap-cluster :markers="markers">
        <template #marker="marker">
          <div style="color:red;" @click="clickMarker(marker)">asdfas</div>
        </template>
        <template #default="{markerNum}">
          <div style="color:yellow;">
            点{{markerNum}}
          </div>
        </template>
      </tmap-cluster>
      <tmap-info-window :position="infoWindow.position" :keyData="infoWindow.data" :visible="infoWindow.visible">
        <template #default="marker">
          <div>
            <p @click="closeMarker(infoWindow)">
              sadfasdfa
            </p>
            
            <div style="color:yellow;" >{{infoWindow}}</div>
            <div>{{marker}}</div>
          </div>
            
        </template>
      </tmap-info-window>
      
      <!-- <tmap-cardinal-arrow :points="markers.map(v =>v.position)" />
      <tmap-polygon :points="markers.map(v =>v.position)" />
      <tmap-polyline :points="markers.map(v =>v.position)" /> -->


   </tmap>
  </div>
</template>

<script>

  export default {
    name: 'app',
    data () {
      return {
        markers:[],
        infoWindow:{
          position:[],
          data:{},
          visible:false
        }
      }
    },
    mounted () {
      setTimeout(()=>{
        for (var i = 0; i < 1000; i++) {
          let lng = 104.06 - (Math.random() * 1).toFixed(6);
          let lat = 30.67	 - (Math.random() * 1).toFixed(4);
          var point = [lng, lat];
          this.markers.push({
            position:point,
            data:{
              name:lng
            },
          })
        }
      
      },2000)
    },
    methods: {
      clickMarker(marker){
        this.infoWindow.position = marker.position
        this.infoWindow.data = marker.keyData
        this.infoWindow.visible = true
        
      },
      closeMarker(){
        this.infoWindow.visible = false
      }
    }
  }
</script>

<style scoped>
  

</style>
